### ISSUE TITLE
With Kirby 4.3, an outdated version is displayed as the installed version

### ISSUE THREAD

**Issue by gbdesign2023** [tobimori/kirby-seo#100]
With Kirby 4.3, an outdated version of your plug-in is displayed as the installed version:
<img width="355" alt="Bildschirmfoto 2024-06-14 um 00 06 26" src="https://github.com/tobimori/kirby-seo/assets/140849227/b5614205-d287-459f-965e-72edcb6a7318">

With Kirby 4.2, the display of the version number works as expected:
<img width="683" alt="Bildschirmfoto 2024-06-14 um 00 06 50" src="https://github.com/tobimori/kirby-seo/assets/140849227/ca493560-ae9b-49ab-b10c-645d3e291858">

I don't know whether the bug is in your plug-in or in the new Kirby version.

**Comment by tobimori** [comment]
It works on 4.3.0 for me, I asked the Kirby team on Discord, it's most likely a CDN issue and will fix itself in the future.

**Comment by tobimori** [comment]
From @lukasbestle on Discord:

```
Yeah, but 4.2 used the version from composer.json, while 4.3 prefers the version from vendor/composer/installed.php.
```

So this behaviour can happen when you installed the 1.0.0-rc.1 via composer, and then updated manually by overwriting the plugin files instead of running `composer update`.
