### ISSUE TITLE
Sitemap generation fails for subfolder installs

### ISSUE THREAD

**Issue by nilshoerrmann** [tobimori/kirby-seo#101]
If a site is installed in a subfolder, e. g. `example.com/my-site`, the generation of the sitemap will fail because the XSLT path is hardcoded to `/sitemap.xsl` which resolves to `example.com/sitemap.xsl` instead of `example.com/my-site/sitemap.xsl`. See:

https://github.com/tobimori/kirby-seo/blob/1175d79fedfc7d4dc43a1d43bb28e5ea187e5ed8/classes/Sitemap/Sitemap.php#L69

**Comment by tobimori** [comment]
Duplicate of #88
