### ISSUE TITLE
Invalid section type

### ISSUE THREAD

**Issue by SeashoreStudio** [tobimori/kirby-seo#105]
Hi,

Trying to install the plugin. Yet getting the error you can see with the attached screenshot. I installed through composer and here's the blueprint file which just shows I've used the example from the installation docs. Probably a really easy fix but I can't understand why it's not working.

`sections:
      seo: seo/site
      albums: sections/albums
      clients: sections/clients
      statements: sections/statements`

Thanks.
![Screenshot 2024-07-25 at 10 25 49](https://github.com/user-attachments/assets/91df29c2-3c8f-42de-bdd8-311231b5a068)

**Comment by tobimori** [comment]
It's not a section but a tab. Please read the docs again
