### ISSUE TITLE
metaDescription - dynamic from field

### ISSUE THREAD

**Issue by Messa1** [tobimori/kirby-seo#110]
It's more of a question than a bug.

When I use code like this - Will I see the tags in the preview of your plugin? Or am I just changing the output of the SEO field?

```
<?php
// site/models/template.php

use Kirby\Cms\Page;

class TemplatePage extends Page
{
	public function metaDefaults(string $lang = null): array
	{
		$content = $this->content($lang);

		return [
			'metaDescription' => $this->categories() . ' ' . $content->summary(),
		];
	}
}
```

**Comment by tobimori** [comment]
It should be visible in the Google preview but not as placeholder in the field
