### ISSUE TITLE
Class "tobimori\Seo\Meta" not found

### ISSUE THREAD

**Issue by paubou** [tobimori/kirby-seo#116]
Hey;
The plugin is working perfectly locally on php 8.3.

But on a apache public server I have the error: 
`Class "tobimori\Seo\Meta" not found`
from `kirby-seo/config/pageMethods.php`.

Kirby version is 4.4.1.
Tried cleaning the cache.

**Comment by Clemens05** [comment]
Hi,

I also ran into the same error. It also works perfectly locally.

How exactly do I update composer autoload on my server?

Kind regards

Clemens
