### ISSUE TITLE
Error message after installing in Kirby 5

### ISSUE THREAD

**Issue by sgerads** [tobimori/kirby-seo#125]
Hi, 
I just installed your plugin on the latest Kirby 5 beta version and I am getting the following error. I am not sure what exactly it means.
<img width="631" alt="Bildschirmfoto 2024-12-27 um 22 32 16" src="https://github.com/user-attachments/assets/48ca4727-613a-46a7-8de1-ca77bb032064" />

**Comment by tobimori** [comment]
Yes, there is no working Kirby 5 version yet.

**Comment by sgerads** [comment]
Ah ok., I thought because of the index.php, that you only support Kirby 5 and higher: 
```
if (
	version_compare(App::version() ?? '0.0.0', '5.0.0-beta.1', '<') === true ||
	version_compare(App::version() ?? '0.0.0', '6.0.0', '>') === true
) {
	throw new Exception('Kirby SEO requires Kirby 5');
}
```

Do you plan on upgrading it?

**Comment by tobimori** [comment]
Yes, there will be a 5.0 compatible release. However, there's still too many moving parts for it to be finished. Please only consider the actual versioned releases "ready-to-use".
