### ISSUE TITLE
No route found for path

### ISSUE THREAD

**Issue by kiahreading** [tobimori/kirby-seo#20]
Hello, the following error is being thrown in the panel on a page that is nested 3 levels deep. DO you know how I could go about debugging it?

`No route found for path: "k-seo/retreats+portugal/registration/robots" and request method: "POST"`

![Screen Shot 2023-06-12 at 2 43 54 pm](https://github.com/tobimori/kirby-seo/assets/30306309/2514874a-e7ed-40b6-bdda-b9633fb0fe0a)

Thanks!

**Comment by tobimori** [comment]
Hi - this should've been fixed with https://github.com/tobimori/kirby-seo/releases/tag/0.3.2. Can you confirm that you're on the latest version?

**Comment by kiahreading** [comment]
Hey, yeah I can confirm I am using 0.3.2, just updated it today.

**Comment by tobimori** [comment]
alright, thanks, i'll get it fixed this evening

**Comment by kiahreading** [comment]
Thanks a lot @tobimori

**Comment by kiahreading** [comment]
Thanks @tobimori
