### ISSUE TITLE
Allow for URLs & Assets in ogImage 

### ISSUE THREAD

**Issue by andreasba** [tobimori/kirby-seo#24]
I was wondering if you are planning to add dynamic og image generation to the plugin at any time? [There is a tutorial on getkirby.com](https://getkirby.com/docs/cookbook/content/dynamic-og-images) using content representations and before building it myself, I wanted to check with you. I hope that is alright.

Thanks
Andreas

**Comment by tobimori** [comment]
I'll definitely add this sometime in the future (or it might be separated into a different plugin), although my approach will be a bit different to the Kirby one. 

My plan is to use [Browsershot](https://github.com/spatie/browsershot) which uses a headless Chrome browser under the hood to render an HTML document to an image. This will not work on some servers, especially shared hosting, as it needs puppeteer to be installed. The plugin will provide the framework integration & baseline, so you'll just have to add a snippet to a specific folder, style it, and it should render it automatically. 

I'm pretty busy with client work atm and the project where I need this will most likely still take a few more months, so this is not a priority for now.

Given that the Kirby Cookbook approach is very different from the route I'm going to take, and also harder but less flexible, there won't be a *direct integration*, but you should be able to use it already by providing a `metaDefaults()` function in a page model and returning an array with `ogImage` set to your dynamic og image.

**Comment by andreasba** [comment]
Thanks for your quick response. While your approach sounds technically very nice, it would not be for me anyway since I am running on shared webhosting as are lots of other people with smaller projects I believe, so the content representation will do just fine for now :) Thanks!

PS: Please also consider that using too many other third party libraries bloats up this plugin a lot and increases the security footprint a lot. When I hear "chrome browser" in a plugin, I run away very quickly ;)

**Comment by andreasba** [comment]
May I ask for your input please @tobimori ?

I tried a very simply model according to your suggestions like this:

`<?php

class AboutUsPage extends Page {


    function metaDefaults() {

        return ['ogImage' => $this->page()->url().'.png'];
    }

}

?>`

But in the panel the ogImage stays empty.

What am I doing wrong?

If important: I am running a multilang site.

Thanks
Andreas

**Comment by tobimori** [comment]
Hi there,

it seems like the plugin currently expects a Field that resolves a file object. So I'll have to publish another update that allows URLs.

I'll add it to my priority list and will get it done asap.

**Comment by andreasba** [comment]
One more idea @tobimori : It would be awesome if I could set this default globally without a Page Model via the config.php file. Currently, I have to create a page model for each page just to set the default.

**Comment by tobimori** [comment]
You should be able to do that by providing it in an option with the key `tobimori.seo.default.ogImage`

**Comment by andreasba** [comment]
Yes sorry I meant something different. I was not talking about a global default image but a page specific image which is defined by its URL/pagename. Background: I am dynamically generating the ogImage for each language and save it on the disk once a page/title is updated - because only in this way the SEO plugin can actually work with it (if it is an actual file on the disk).

**Comment by tobimori** [comment]
You can set the option to a function where you have access to the page content.
You can see some examples here: https://github.com/tobimori/kirby-seo/blob/main/index.php#L27

**Comment by andreasba** [comment]
I actually had an even better idea :) Well better idk but easier ;) I use a hook to simply write the UUID of the generated image directly to the content file of the page. This works perfectly and is clean and easy with a couple of lines of code only 👍
