### ISSUE TITLE
Keyword Support

### ISSUE THREAD

**Issue by CoderofOne** [tobimori/kirby-seo#26]
I know keywords are not really used anymore within SEO but clients still think so. Is there an easy way to include keywords input field and have them output in the meta data?

**Comment by tobimori** [comment]
I will not add keywords support for the exact reasons you mentioned, however you could add support yourself in the following steps:

1. Create your own `seo/page` blueprint tab, based on [the one the plugin provides](https://github.com/tobimori/kirby-seo/blob/main/blueprints/page.yml). Depending on where you want the field to be, you might also have to edit and copy the corresponding group blueprint parts.
2. Add the meta tag to your template. 
```php
<meta name="keywords" content="<?= $page->metadata()->keywords() ?>">
```
3. Benefit from the plugins' Meta Cascade and have keywords support :)

**Comment by CoderofOne** [comment]
Tobi,

Thanks for the reply and steps needed. Much appreciated.
