### ISSUE TITLE
Feedback regarding layout of Global Settings in Panel

### ISSUE THREAD

**Issue by andreasba** [tobimori/kirby-seo#28]
Good afternoon,

when using the OOB blueprints, there are three main sections added:

1. Global SEO Settings
2. Global Open Graph Settings
3. Robots Directives
(4. and Social Media Accounts)

and I found that they confuse me:

- The Global SEO Settings seem not to be global - at least, when I enter the following on the blueprint of the site.yml
![image](https://github.com/tobimori/kirby-seo/assets/15323226/b8804c6d-594f-4b03-b23a-e063ede0a8d1)
.. and I go to the next page, the title and the page description is empty: 
![image](https://github.com/tobimori/kirby-seo/assets/15323226/e2ff4622-10e9-440d-ad26-36c2c86143ad)
(I would expect the same content there)
- The same goes for the "Global Open Graph Settings" - which are only partly global, partly page specific. I would suggest a split up here between the global settings on site.yml and the page specific once only showing on each page if thi is possible. If it is not possible, I would put the global settings on the bottom.
- What I also do not understand is the Robots Directives section. It states the global default but does not select it - and thus the "required field" validator pops up meaning I have to do a manual selection for each page which defies the whole purpose of having global settings which can be overwritten on the page level, no? :)
- The Social Media Accounts also do only make sense on a global level, not page level

Just my two cents :)

Andreas

**Comment by tobimori** [comment]
It appears you did make a mistake with adding the blueprints to your pages.

There are two blueprint tabs: `seo/site` and `seo/page`.
`seo/page` should be added to the page blueprints and does not contain "global settings".

**Comment by andreasba** [comment]
A clear case of RTFM - sorry :)
