### ISSUE TITLE
Meta cascade does not work with site globals

### ISSUE THREAD

**Issue by MaluNoPeleke** [tobimori/kirby-seo#30]
After installing this plugin and setting it up page updates remind me of defining specific SEO field even if I have set them already in the global site options:
![image](https://github.com/tobimori/kirby-seo/assets/1446541/598e6801-de52-4dcd-ab8b-afbfd0552e1c)
Page update:
![image](https://github.com/tobimori/kirby-seo/assets/1446541/3e9f006b-2510-4b7e-a29c-10cb4caf00c1)
Page SEO tab:
![image](https://github.com/tobimori/kirby-seo/assets/1446541/49f29825-e517-4400-b714-c8f3cd0df6d0)

**Comment by tobimori** [comment]
This is unfortunately an issue with how Kirby handles `default` selects when fields get added later. 
It works for new pages, and I'm unable to fix this without "breaking" my UX.

**Comment by tobimori** [comment]
As you're switching from Meta Knight to this plugin - if you're willing to provide a migration script (for Kirby CLI) that handles this I'd accept a PR.
