### ISSUE TITLE
Defaults for Robots settings not applied for pages created before plugin was active

### ISSUE THREAD

**Issue by jonasfeige** [tobimori/kirby-seo#32]
Not sure if this is actually a bug or intended:

On pages that were created BEFORE I installed the plugin, the Robots settings are not automatically set to Default, which is why an error message pop ups when trying to update and save those pages. I know this is the default Kirby behavior, but it's quite confusing for my clients. Maybe this can be solved with a hook?

Loving the plugin, by the way!

**Comment by tobimori** [comment]
I'd accept a migration script for Kirby CLI that solves the issue as PR, see https://github.com/tobimori/kirby-seo/issues/30#issuecomment-1672957250

**Comment by jonasfeige** [comment]
I'll give this a crack when I get a chance.

**Comment by tobimori** [comment]
Note to myself: Maybe there's a way to solve this easily with a `page.save:before` hook.

**Comment by tobimori** [comment]
After looking at it again, to my understanding this idea is impossible to solve with hooks, because validation always occurs before running the hook which will prevent running the hook if the fields are not set yet and the page is not a draft.
