### ISSUE TITLE
Date format strftime has typo

### ISSUE THREAD

**Issue by MaluNoPeleke** [tobimori/kirby-seo#33]
How to use `strftime` as date format?
If I add this to the config it doesn't recognize the date format correctly:

    'tobimori.seo' => [
      'generateSchema' => true,
      'canonicalIncludesWWW' => false,
      'dateFormat' => 'strftime',
      'robots' => [
          'active' => true,
          'content' => [
              '*' => [
                  'Allow' => ['/'],
                  'Disallow' => ['/kirby', '/panel', '/content']
              ]
          ]
      ]
    ],

**Comment by tobimori** [comment]
You'll have to set a global `date.handler` in Kirby and the plugin will automatically use it with `tobimori.seo.dateFormat` as format.

**Comment by MaluNoPeleke** [comment]
It is set to this already but then the output looks like this:
`<meta content="%Y-08-10" name="date">`

**Comment by MaluNoPeleke** [comment]
config.php looks like this now:

```
    'date'  => [
      'handler' => 'strftime'
    ],

    'tobimori.seo' => [
      'generateSchema' => true,
      'canonicalIncludesWWW' => true,
      'robots' => [
          'active' => true,
          'content' => [
              '*' => [
                  'Allow' => ['/'],
                  'Disallow' => ['/kirby', '/panel', '/content']
              ]
          ]
      ]
    ],
```

**Comment by tobimori** [comment]
I see there's a typo in the plugin. You can manually set `dateFormat` to `%Y-%m-%d` for now.

**Comment by MaluNoPeleke** [comment]
Okay, thanks for the confirmation. Then I will set it manually to %dd.%mm.%yyyy for now.

**Comment by tobimori** [comment]
This will be fixed in the next release

**Comment by MaluNoPeleke** [comment]
Okay, great, then I can remove the manual formatting again, correct?

**Comment by tobimori** [comment]
yeah
