### ISSUE TITLE
Selectively allow/disallow specific robots

### ISSUE THREAD

**Issue by andreasba** [tobimori/kirby-seo#35]
It would be great if one could selectively allow or disallow specific robots on the site, such as the GPTBot: https://www.theverge.com/2023/8/7/23823046/openai-data-scrape-block-ai

**Comment by tobimori** [comment]
I don't think it's possible to disallow certain User Agents using the Meta Attribute we're using for page specific robots settings, although you can always customize the robots.txt in your config - and exclude the GPTBot there
https://github.com/tobimori/kirby-seo#options

I will not add a feature that checks all pages for it's robots settings and then aggregates them in a robots.txt, seems kinda pointless to me.
