### ISSUE TITLE
Error when using $site->schema('WebSite')

### ISSUE THREAD

**Issue by andreasba** [tobimori/kirby-seo#37]
When I do the following in my Kirby 4 Alpha:

`$site->schema('WebSite')
    ->url($page->url())
    ->description($site->Ogdescription())
    ->copyrightYear(e(date("Y") === '2023', '2023', '2023 - ' . date("Y")))
    ->copyrightHolder($site->companyLegalName()
); `

I get the following error:

Error thrown with message "Call to a member function id() on null"

![image](https://github.com/tobimori/kirby-seo/assets/15323226/e0d470da-bd47-4ce4-9181-d5902ae44908)

Am I doing something wrong or is this a bug?

I am calling this in the header of my template, 

`<?php snippet('seo/schemas'); ?>`

is included in the footer of my template.

**Comment by tobimori** [comment]
Will be fixed in the next release
