### ISSUE TITLE
upgrading to 0.4.0 with kirby 4.0.0-alpha.7 throws error

### ISSUE THREAD

**Issue by mourique** [tobimori/kirby-seo#39]
i just upgraded your plugin to 0.4.0 on my first kirby 4 project with 4.0.0-alpha.7 and it throws the Exception: »Kirby SEO requires Kirby 4«. It seems to me like the version check does not work correctly.

**Comment by tobimori** [comment]
This is intentional. Please use kirby 4.0.0-beta.1+ or stay with kirby-seo 0.3.4.
