### ISSUE TITLE
Composer updates need to be applied manually

### ISSUE THREAD

**Issue by bnomei** [tobimori/kirby-seo#4]
if you do versions below 1 composer behaves diverently than npm etc. i will NOT upgrade between minor versions. there is not warning - nothing.

so
0.1.x will not be upgraded to 0.2 if you do `composer upgrade`.

**Comment by tobimori** [comment]
Thanks for the heads-up. I plan to keep it this way until most issues have been ironed out, and the plugin is battle-tested.
A 1.0.0 release will follow in a few months, when I also implemented most of the roadmap features.

**Comment by tobimori** [comment]
Solved with the upcoming release
