### ISSUE TITLE
[K4] Translate issue

### ISSUE THREAD

**Issue by afbora** [tobimori/kirby-seo#40]
### First load
![screen-capture-1688-seo - Mægazine-localhost](https://github.com/tobimori/kirby-seo/assets/3393422/0da56618-4764-45b7-864d-076608151b40)

### After click an option
![screen-capture-1689-seo - Mægazine-localhost](https://github.com/tobimori/kirby-seo/assets/3393422/da2f8b75-c407-4c1b-95f0-3ff0279155e8)

### Info
- Kirby 4.0.0-beta.1
- Kirby Seo 0.4.0
- Chrome 117
- Windows 10

**Comment by tobimori** [comment]
I assume this is related to #21
