### ISSUE TITLE
overwrite for seo image

### ISSUE THREAD

**Issue by bnomei** [tobimori/kirby-seo#42]
using the `tobimori.seo.default` one can overwrite the metaTitle or ogDescription but not which field gets resolved for the opengraph image. that would be handy to have to reuse an existing field.

**Comment by tobimori** [comment]
You should be able to overwrite every field using its key. (`ogImage`, set it to a closure that returns a field ideally) 
Although make sure the Site field is not set. 
You can also use Page models to overwrite the image at a higher point in the cascade.
