### ISSUE TITLE
Plugin doesn't work

### ISSUE THREAD

**Issue by MaluNoPeleke** [tobimori/kirby-seo#44]
After downgrading to 0.3.4 (because of using Kirby 3.9.7) the plugin doesn't work anymore:
![image](https://github.com/tobimori/kirby-seo/assets/1446541/90ac1eaf-65dc-4f68-9ac4-d79ec3caebe2)
The code in the site.yml still is the same:
![image](https://github.com/tobimori/kirby-seo/assets/1446541/a33bcbaa-060e-459f-bc64-a1baf2ce2b7f)
On page level:
![image](https://github.com/tobimori/kirby-seo/assets/1446541/ee96282a-978c-415d-86cd-366a76ed89d2)
Any hints how to fix this?

**Comment by tobimori** [comment]
Does it work with Kirby 3.9.6?

**Comment by tobimori** [comment]
I just tested 0.3.4 on a 3.9.7 site and it seems to work fine to be. Have you found out anything else?

**Comment by MaluNoPeleke** [comment]
Sadly no. How can I debug the issue further?

**Comment by tobimori** [comment]
Do you have any other plugins installed that might interfere with it? Do you use composer for installation?
It seems to fail in the plugin registration progress.

**Comment by tobimori** [comment]
I'll close this for now, let me know if you have any more information
