### ISSUE TITLE
Pages with slug that contains 'site' only allowing selection of site-level OG images

### ISSUE THREAD

**Issue by whitmoa** [tobimori/kirby-seo#55]
I'm having an issue where some pages are only offering site-level images for selection when choosing an Open Graph image. I can, of course, work around it by adding the relevant images to the root but that's not ideal when handing sites over to clients.

- **Example 1:** I have three pages using the blueprint `primary.yml`, which has `seo: seo/page` included at the bottom. Two of the pages behave correctly and allow me to choose an OG image from the list of page files. But the other page only allows selection of images at the root.
- **Example 2:** another example is that three pages use the blueprint `project.yml`, which also has `seo: seo/page`. However, all three pages only offer the root images to chose from for the OG image.

This is my page called _Websites_, which uses `primary.yml`. You can see the list of page images to the right...

![image](https://github.com/tobimori/kirby-seo/assets/153773853/fdadc69a-47cf-4b97-9e4c-d94323ba3f0b)

But this is what I see when trying to select an OG image (none of the page images and only a root image)...

![image](https://github.com/tobimori/kirby-seo/assets/153773853/dc773d63-2680-4c53-9781-fc9ad74368a7)

I cannot find  any reason why pages using the same blueprint are behaving differently with the OG image selection. Please advise.

**Comment by tobimori** [comment]
It's because your pages' slug contains the word 'site' which I'm using to identify the site [here](https://github.com/tobimori/kirby-seo/blob/main/blueprints/fields/og-image.php#L11C85-L11C85) 😄

**Comment by whitmoa** [comment]
Yes, that'll be it! The three 'project' pages are website case studies, so they all have "site" in the title. too.
