### ISSUE TITLE
Error in multi-language sitemap creation

### ISSUE THREAD

**Issue by JuKra00** [tobimori/kirby-seo#61]
Hey Tobias, thanks for your great work with the plugin.

Found a bug in 1.0.0-beta.2 using kirby 4.0.2 on php 8.2.13

During sitemap creation on a multilingual website, there is an error "Call to a member function toArray() on array".
The error occurs in `config/options/sitemap.php:31` and is caused by the map function which converts `Kirby\Languages` to a collection of arrays.

It can be solved by using a `Kirby\Toolkit\Obj` instead of a simple array as return value of the map.

**Comment by tobimori** [comment]
Thanks for your issue and the proposed fix; i'll take a look at this in a few days.

**Comment by tobimori** [comment]
honestly i still don't understand why this is necessary but your fix works perfectly
