### ISSUE TITLE
Sitemap option to exclude unlisted pages

### ISSUE THREAD

**Issue by jonasfeige** [tobimori/kirby-seo#68]
It would be great to have an option to exclude unlisted pages from the sitemap. I know this can be achieved with the generator function, but maybe it could also be a default option.

**Comment by tobimori** [comment]
The default generator function relies on the robots settings the plugin provides:
https://github.com/tobimori/kirby-seo/blob/main/config/options/sitemap.php#L8C1-L9C1
by default, robots settings follow the page status. it should already work that way.

**Comment by jonasfeige** [comment]
I see. I had the robots settings under `site` set to `yes` instead of `default` for some reason.
I think your logic makes sense, just wonder if another pointer to the robots settings might make sense in the sitemap docs.

**Comment by tobimori** [comment]
ah yes, in that case the site default overrides the options fallback according to the cascade. i'll add it to the docs.
