### ISSUE TITLE
Automatically add one canonical tag per page

### ISSUE THREAD

**Issue by PierreClementCazon** [tobimori/kirby-seo#72]
Hello, thank you for your work on this plugin. 

Ideally, a canonical tag should be automatically added to each page by default, so that each page can be modified if necessary.

Best regards.

**Comment by tobimori** [comment]
This is already included.

**Comment by PierreClementCazon** [comment]
Yes, but it doesn't seem to work properly.

The canonical tag should look like this: 

`<link rel="canonical" href="https://www.site.com">`

But the one in the source code looks like this: 

`<meta content="https://www.site.com" name="canonical">`

Best regards.

**Comment by tobimori** [comment]
That's weird, for me it's correctly added as link tag. Which version do you use?

**Comment by PierreClementCazon** [comment]
I'm using version 0.4.0 of the plugin.

**Comment by tobimori** [comment]
This was fixed in 1.0-rc
