### ISSUE TITLE
sitemap in 0.4.0  does not work 🤷🏻‍♂️

### ISSUE THREAD

**Issue by squareclouds** [tobimori/kirby-seo#76]
not sure if i am doing something wrong but, the sitemap does not work in the current 0.4.0 release. inside "config" the whole folder 'options' is missing, meaning the sitemap.php is also missing. the release candidates have the folder and hence everything works fine here.

**minor detail which does not bother that much...**
the release candidate sitemap does not work on a local environment though, i keep getting syntax errors. i use mamp on mac and codekit. nor the direct localhost url nor codekits autorefresh url work. but again, at least it works live so no biggie.

**Comment by tobimori** [comment]
The sitemap is part of 1.0 so it makes sense that it doesn't work in 0.4.0.
