### ISSUE TITLE
Inheritance and validation

### ISSUE THREAD

**Issue by LuckyRessource** [tobimori/kirby-seo#80]
The following example:

- Page 1 has robots settings and inheritance set for it.
    - Page 2 (child of page 1) Without own robots settings but with inheritance of the robots settings
        - Page 3 (child of page 2) Completely without SEO settings
All pages are public.

If something is to be saved on page 3, the validation error always occurs. The robots fields must be filled. But the settings for this were actually inherited from the parent pages. The meta-Robtos statement is inherited correctly in the output in the front end, only saving in the back end no longer works, which invalidates the principle of inheritance.

**Comment by tobimori** [comment]
This is to be expected. Please select the first value in the Robots fields.
Kirby does not have any logic or way to apply the default value to a page after it's creation, until something in Core changes, this issue will stay.
