### ISSUE TITLE
Forward /sitemap to /sitemap.xml

### ISSUE THREAD

**Issue by andreasba** [tobimori/kirby-seo#84]
Hi Tobi,

first of all a huge thanks for the great update of the plugin 👍

In my humble opinion, the sitemap generator has three things I would reconsider:

1. The docs clearly state that it uses the state of the robots.txt but in cases where I have not set that because it is a static page which is Unlisted, IHMO the sitemap should still not display it - it is unlisted for a reason :)
2. I do not believe in security through obscurity but blasting out the Kirby CMS reference on the sitemap.xml is too much for me - it is not like any humans would read that unless they are potentially up to something
3. I would recommend to ship a pre-build route, permanently redirecting domain.com/sitemap to domain.com/sitemap.xml

Thanks
Andreas

**Comment by tobimori** [comment]
1. Not sure what you mean by that. In case a page is unlisted, it will not be shown in the sitemap with the default configuration of the plugin.
2. It's ***very easy*** to figure out if a site is using Kirby CMS, no matter if you have Kirby SEO (with enabled sitemap) installed or not. Wappalyzer and other tools easily detect it already. If you're actually concerned about this, you can provide a custom stylesheet by overriding the template file.
3. This is a good suggestion. I'm actually often reading sitemaps manually, hence I made sure to polish the stylesheet so it's delightful to use.
