### ISSUE TITLE
Disable robots: does not work with only  'tobimori.seo.robots.active' => false,

### ISSUE THREAD

**Issue by wdebusschere** [tobimori/kirby-seo#87]
Disabling the robots only works when i have both items in my config

    'tobimori.seo.robots.active' => false,
    'tobimori.seo.robots.pageSettings' => false,

**Comment by tobimori** [comment]
since page settings is set in [options.php](https://github.com/tobimori/kirby-seo/blob/main/config/options.php), the fallback doesn't work
https://github.com/tobimori/kirby-seo/blob/main/blueprints/fields/robots.php#L10
