### ISSUE TITLE
Google preview title not correct

### ISSUE THREAD

**Issue by wdebusschere** [tobimori/kirby-seo#90]
Kirby CMS 4.1.2
PHP 8.2.7
Apache
tobimori/seo: 1.1.0

For Google: the title is NOT correct
![Screenshot 2024-03-26 at 13 59 08](https://github.com/tobimori/kirby-seo/assets/4136426/a78fa376-5b00-4740-be95-f874ea19af8e)

For Facebook: the title is correct

![Screenshot 2024-03-26 at 13 59 31](https://github.com/tobimori/kirby-seo/assets/4136426/962c3580-1470-4b0a-aa07-8b656617d2fa)

**Comment by wdebusschere** [comment]
Any updates on this?

**Comment by tobimori** [comment]
Haven't prioritized it, since it's not really a breaking bug and I've been working on DreamForm the past two weeks.

**Comment by wdebusschere** [comment]
I would suggest to leave it open then, it's still a bug.

**Comment by tobimori** [comment]
No, I just released 1.1.2 with the fix.
