### ISSUE TITLE
Favicon is not displayed in Google results

### ISSUE THREAD

**Issue by gbdesign2023** [tobimori/kirby-seo#94]

**Comment by tobimori** [comment]
The plugin doesn't do anything related to favicons yet.

**Comment by gbdesign2023** [comment]
@tobimori Sorry. Yes, I realized that afterward and therefore deleted my text. It was due to the favicon plugin from Moritz Ebeling.

**Comment by tobimori** [comment]
I figured so, I just wanted to add this comment so everyone that stumbles upon this can look elsewhere
