### ISSUE TITLE
Sitemap multi-lang out of the box?

### ISSUE THREAD

**Issue by squareclouds** [tobimori/kirby-seo#97]
Kirby 4.2.0
Plugin 1.1.2
----

hello everyone,

i have a 3 lang website. the robots seem to be working, if i change settings i can see them appear instantly. right now i have this:

```
'tobimori.seo.robots' => [
        'active' => true,
        'content' => [
            '*' => [
                'Allow' => ['/', '/sitemap.xml'],
                'Disallow' => ['/kirby', '/panel', '/content']
            ]
        ]
    ],
```

i have two problems/questions though.

1. as you can see i explicitly added "/sitemap.xml" to the allow list since google search console is giving me an error:

Sitemap konnte nicht gelesen werden
Allgemeiner HTTP-Fehler

but this didnt help... i am still getting the error, not sure why. the sitemap is there though.

2. when i visit the sitemap, i only see the german entries

![Bildschirmfoto 2024-06-05 um 16 52 31](https://github.com/tobimori/kirby-seo/assets/9073054/127a8765-fdba-41f1-a1e1-ef611925c857)

it is a tri-language page though, as i mentioned before. did i miss something in the docs? do i have to activate this somehow?

any help is appreciated!

**Comment by squareclouds** [comment]
hm, now i tried to index the home-page and google seems to not be able to access it either, just like the sitemap

![Bildschirmfoto 2024-06-05 um 16 57 10](https://github.com/tobimori/kirby-seo/assets/9073054/ceac33b7-da02-4f95-8fa8-ca710ffd985b)

my robots.txt output looks as followed though

![Bildschirmfoto 2024-06-05 um 17 00 34](https://github.com/tobimori/kirby-seo/assets/9073054/aec203b0-23d4-487a-9175-1cfd54b4f38e)

**Comment by tobimori** [comment]
The sitemap is working as expected, if you look at view-source, you can see all languages: 
`view-source:https://kinderarzt-frohnau.de/sitemap.xml`

**Comment by tobimori** [comment]
For the robots/indexing error - no clue. I have the same setup for 10+ sites and it works perfectly everywhere.

**Comment by squareclouds** [comment]
ah ok, i checked in chrome with view-source: and it shows like you said, so yes, it seems to be only the human readable part thats DE only.

hmmm... ok, strange. i will wait a bit then. the domain was transferred today so maybe the googlebot is still using a cached robots or sitemap from the previous website/owner. could that be it?

**Comment by tobimori** [comment]
I tried fetching the sitemap with the Googlebot User Agent, and there doesn't seem anything wrong there either. So no clue.
![CleanShot 2024-06-05 at 17 33 03@2x](https://github.com/tobimori/kirby-seo/assets/29142128/55bb120c-895a-49c7-a9e9-a5837c0a0380)

**Comment by squareclouds** [comment]
i think it was just a matter of waiting a bit longer, now the sitemap is recognized by search console as well. all good now! thank you!
