### ISSUE TITLE
Hreflang info not correct when using Model to rewrite a URL

### ISSUE THREAD

**Issue by isaactopo** [tobimori/kirby-seo#99]
Hi!
I have this model:
```php
class PostPage extends Page {
  public function url($options = null): string
  {
     return $this->url = page('blog')->url().'/'. $this->slug();
  }
}
```
To rewrite a /blog/YEAR/ and the hreflang for the alternate languages doesn't render well, always renders the actual language:

```html
<link href="https://site.local/blog/newsletter-05-2024-fiscal-03b84b1767" hreflang="ca">
<link href="https://site.local/blog/newsletter-05-2024-fiscal-03b84b1767" hreflang="es">
```

Let me know if you need more info.
Thanks

**Comment by tobimori** [comment]
In this case, the issue lies in your url method which behaves differently to the Kirby built-in one. You need to pass the $options parameter to the `page('blog')->url($options)` and `$this->slug($options)` call. Then it will correctly render the language.

**Comment by isaactopo** [comment]
You're right! Thanks @tobimori
